-- MySQL Script generated by MySQL Workbench
-- Sat Mar 27 12:04:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema car_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_shop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `car_shop` ;

-- -----------------------------------------------------
-- Table `car_shop`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`customers` (
  `customer_number` INT NOT NULL,
  `customer_company_name` VARCHAR(50) NOT NULL,
  `contact_last_name` VARCHAR(50) NOT NULL,
  `contact_first_name` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(50) NOT NULL,
  `address_line_1` VARCHAR(50) NOT NULL,
  `address_line_2` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `postal_code` VARCHAR(15) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `credit_limit` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`customer_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car_shop`.`job_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`job_title` (
  `id` INT NOT NULL,
  `job_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car_shop`.`managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`managers` (
  `manager_number` INT NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `number_of_employees` INT NOT NULL,
  PRIMARY KEY (`manager_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car_shop`.`offices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`offices` (
  `office_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(50) NOT NULL,
  `address_line_1` VARCHAR(50) NOT NULL,
  `address_line_2` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NOT NULL,
  `postal_code` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`office_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car_shop`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`employees` (
  `employee_number` INT NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `job_title_id` INT NOT NULL,
  `manager_number` INT NULL DEFAULT NULL,
  `office_code` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`employee_number`),
  INDEX `fk_job_title` (`job_title_id` ASC) VISIBLE,
  INDEX `fk_manager` (`manager_number` ASC) VISIBLE,
  INDEX `fk_office` (`office_code` ASC) VISIBLE,
  CONSTRAINT `fk_job_title`
    FOREIGN KEY (`job_title_id`)
    REFERENCES `car_shop`.`job_title` (`id`),
  CONSTRAINT `fk_manager`
    FOREIGN KEY (`manager_number`)
    REFERENCES `car_shop`.`managers` (`manager_number`),
  CONSTRAINT `fk_office`
    FOREIGN KEY (`office_code`)
    REFERENCES `car_shop`.`offices` (`office_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car_shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`orders` (
  `order_number` INT NOT NULL,
  `order_date` DATE NOT NULL,
  `required_date` DATE NOT NULL,
  `shipped_date` DATE NULL DEFAULT NULL,
  `status` VARCHAR(15) NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `quantity_ordered` INT NOT NULL,
  `price_each` DOUBLE NOT NULL,
  `customer_number` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_number`),
  INDEX `fk_customer_order` (`customer_number` ASC) VISIBLE,
  CONSTRAINT `fk_customer_order`
    FOREIGN KEY (`customer_number`)
    REFERENCES `car_shop`.`customers` (`customer_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car_shop`.`product_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`product_lines` (
  `product_line` VARCHAR(50) NOT NULL,
  `text_description` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`product_line`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car_shop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`products` (
  `product_code` VARCHAR(15) NOT NULL,
  `product_name` VARCHAR(70) NOT NULL,
  `product_scale` VARCHAR(10) NOT NULL,
  `product_vendor` VARCHAR(50) NOT NULL,
  `product_description` TEXT NOT NULL,
  `quantity_in_stock` INT NOT NULL,
  `buy_price` DOUBLE NOT NULL,
  `selling_price` DOUBLE NOT NULL,
  `product_line` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`product_code`),
  INDEX `fk_product_line` (`product_line` ASC) VISIBLE,
  CONSTRAINT `fk_product_line`
    FOREIGN KEY (`product_line`)
    REFERENCES `car_shop`.`product_lines` (`product_line`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car_shop`.`orders_contain_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`orders_contain_products` (
  `order_number` INT NOT NULL,
  `product_code` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`order_number`, `product_code`),
  INDEX `fk_product` (`product_code` ASC) VISIBLE,
  CONSTRAINT `fk_order`
    FOREIGN KEY (`order_number`)
    REFERENCES `car_shop`.`orders` (`order_number`),
  CONSTRAINT `fk_product`
    FOREIGN KEY (`product_code`)
    REFERENCES `car_shop`.`products` (`product_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `car_shop`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_shop`.`payments` (
  `customer_number` INT NULL DEFAULT NULL,
  `check_number` VARCHAR(50) NOT NULL,
  `payment_date` DATE NOT NULL,
  `amount` DOUBLE NOT NULL,
  INDEX `fk_customer_payment` (`customer_number` ASC) VISIBLE,
  CONSTRAINT `fk_customer_payment`
    FOREIGN KEY (`customer_number`)
    REFERENCES `car_shop`.`customers` (`customer_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
